# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586bcd2ddea64d4b5176e4955b0c328635f5073ba97eaf4fc4abee2d1ca9591987c860f9a6554f622af138efb441c15f2f8f8c0c3f8783b1edc8852cc1a1a382

test:
  secret_key_base: bafee819fdd7269493e73847d3f84a34b0a18e116ad2261e089106bcf83087ab3ababaf8c6d3fb333cbecf1b5f09ebac41ee16eb93db7453154f9b6bc737534e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
